version: 2
jobs:
  test:
    working_directory: ~/NativescriptAppBuild
    docker:
      - image: circleci/node:12.4.2
    steps:
      - checkout

      - run:
          name: Install npm modules
          command: |
            npm i --no-progress;

      - run:
          name: Tests
          command: |
            npm run lint

workflows:
  version: 2
  build_release:
    jobs:
      - test
#          filters:
#            branches:
#              ignore: /.*/
#            tags:
#              only: /.*/
